### ISSUE TITLE
Archive the old Knit2 Yarns repo

### ISSUE THREAD

**Issue by chadfawcett** [knit2yarns/knit2yarns.github.io#29]
This site has been converted to Gatsby and is hosted at https://github.com/TwoStoryRobot/knit2yarns

This repo should be archived once confirmed it's safe to do so.

**Comment by chrisfosterelli** [comment]
Can we archive this now @chadfawcett?

**Comment by chadfawcett** [comment]
Yup

**Comment by chrisfosterelli** [comment]
Will do!
